# KBMP2020_ASVIndicators
# Kat Beilsmith
# University of Chicago Department of Ecology and Evolution, Bergelson Lab
# Summer 2020

####################################################################################################################################################

# The goal here is to find the ASVs associated with particular conditions-- tissues, stages, sites, and years. We do this using the signassoc 
# function of the indicspecies package. This function calculates the indicator value index (IndVal), based on the product of two probabilities: 
# (1) the probability that a sample belongs to a condition given the ASV is found there and 
# (2) the probability that an ASV is present if a sample is from a condition. 
# These associations are calculated independently for each ASV for one condition at a time. The null hypothesis that no relationship exists between 
# ASVs and conditions is tested by comparing the empirical index with a distribution generated by randomly permuting the ASV by sample 
# presence-absence table. A two-tail p-value is used to select ASVs that are significantly more or less frequently observed in sampled belonging to 
# a given condition.
# Documentation: https://cran.r-project.org/web/packages/indicspecies/vignettes/indicspeciesTutorial.pdf
# Reference: https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1890/08-1823.1

# We then examine whether these ASVs are pervasive (present in more than one tissue type) or recurrent (present at more than one stage).

####################################################################################################################################################

# Copy phyloseq object
PA_R_physeq <- R_physeq

# Convert ASV counts to presence/absence (P/A) by replacing all values > 0 with 1
OTUCounts <- as.data.frame(otu_table(PA_R_physeq))
OTUCounts[OTUCounts>0] <- 1

# Check data
# taxa_sums(PA_R_physeq)[1:10]
# rowSums(OTUCounts)[1:10]

# Replace OTU table with P/A table
otu_table(PA_R_physeq) <- otu_table(as.matrix(OTUCounts),taxa_are_rows=TRUE)

# taxa_sums(PA_R_physeq)[1:10]

# Make categories for rhizosphere vs. phyllosphere.
sample_type <- data.frame(sample_data(PA_R_physeq))
sample_type$Sphere <- ifelse(sample_type$PlantPart=="Roots","Rhizo","Phyllo")

# Variables for grouping samples into habitat types
category_list <- c("PlantPart","Sphere","Stage","Site","Year") 

for(group in category_list){ # For each grouping variable
  print(group)
  group_list <- as.character(sample_type[order(sample_type[,group]),][,group]) # Order samples by group and get the names of the groups to which the ordered samples belong
  group_order <- as.character(rownames(sample_type[order(sample_type[,group]),])) # Get the order of samples arranged by group
  species_matrix <- t(otu_table(PA_R_physeq)) # Transform the ASV matrix so that ASVs are columns and samples are rows
  sample_type_ordered <- species_matrix[match(group_order,rownames(species_matrix)),] # Order the rows (samples) by group
  # Permutation test to find species significantly associated with sample group:
  prefsign = signassoc(sample_type_ordered, cluster=group_list, mode=0, alternative = "two.sided",control = how(nperm=9999)) 
  df <- as.data.frame(prefsign) # Put permutation test results into dataframe
  indicator_ASVs <- df[df$psidak < 0.01,] # Select results with desired p-value threshold
  assign(paste(group,"Indicators",sep="_"),indicator_ASVs) # Store results
  write.table(indicator_ASVs,file=paste("~/Documents/KBMP2020_Microbes/Outputs/",paste(group,"Indicators",sep="_"),sep=""), sep="\t", row.names=TRUE,quote=FALSE) # Save results
}

# Make dataframe for storing results
VennFrame <- NULL
VennFrame <- data.frame(matrix(ncol = length(category_list), nrow = length(colnames(species_matrix))),stringsAsFactors = FALSE)
VennFrame  <- setNames(data.frame(VennFrame), category_list)
rownames(VennFrame) <- colnames(species_matrix)

for(group in category_list){
  VennFrame[,group] <- ifelse(rownames(VennFrame) %in% rownames(get(paste(group,"Indicators",sep="_"))),1,0)
  # table(VennFrame[,group])
}

# ASVs significantly associated with tissue type: 460
colSums2(as.matrix(VennFrame[,"PlantPart"]))

# ASVs significantly associated with phyllosphere vs. roots: 418
colSums2(as.matrix(VennFrame[,"Sphere"]))

# ASVs significantly associated with stage: 268
colSums2(as.matrix(VennFrame[,"Stage"]))

# Most of the ASVs significantly associated with tissue type are captured by just comparing the roots to the phyllosphere (overlap 355)
venn(VennFrame[,c("PlantPart","Sphere")])

# Most of the ASVs significantly associated with developmental stage are also associated with the tissue type (overlap 204)
venn(VennFrame[,c("PlantPart","Stage")])

# The "best" column indicates the tissue with the strongest association by the number of the column. 
# Add the name of the tissue for which each ASV is an indicator in the "TopTissue" column.
PlantPart_Indicators$TopTissue <- NA
PlantPart_Indicators[PlantPart_Indicators$best==1,]$TopTissue <- colnames(PlantPart_Indicators)[1]
PlantPart_Indicators[PlantPart_Indicators$best==2,]$TopTissue <- colnames(PlantPart_Indicators)[2]
PlantPart_Indicators[PlantPart_Indicators$best==3,]$TopTissue <- colnames(PlantPart_Indicators)[3]
PlantPart_Indicators[PlantPart_Indicators$best==4,]$TopTissue <- colnames(PlantPart_Indicators)[4]
PlantPart_Indicators[PlantPart_Indicators$best==5,]$TopTissue <- colnames(PlantPart_Indicators)[5]
PlantPart_Indicators[PlantPart_Indicators$best==6,]$TopTissue <- colnames(PlantPart_Indicators)[6]

# Same for developmental stage.
Stage_Indicators$TopStage <- NA
Stage_Indicators[Stage_Indicators$best==1,]$TopStage <- colnames(Stage_Indicators)[1]
Stage_Indicators[Stage_Indicators$best==2,]$TopStage <- colnames(Stage_Indicators)[2]
Stage_Indicators[Stage_Indicators$best==3,]$TopStage <- colnames(Stage_Indicators)[3]
Stage_Indicators[Stage_Indicators$best==4,]$TopStage <- colnames(Stage_Indicators)[4]
Stage_Indicators[Stage_Indicators$best==5,]$TopStage <- colnames(Stage_Indicators)[5]
Stage_Indicators[Stage_Indicators$best==6,]$TopStage <- colnames(Stage_Indicators)[6]

# Make dataframe for storing results
VennFrame2 <- NULL
VennFrame2 <- data.frame(matrix(ncol = length(unique(PlantPart_Indicators$TopTissue)), nrow = length(colnames(species_matrix))),stringsAsFactors = FALSE)
VennFrame2  <- setNames(data.frame(VennFrame2), unique(PlantPart_Indicators$TopTissue))
rownames(VennFrame2) <- colnames(species_matrix)

for(tissue in unique(PlantPart_Indicators$TopTissue)){
  # print(tissue)
  VennFrame2[,tissue] <- ifelse(rownames(VennFrame2) %in% rownames(PlantPart_Indicators[PlantPart_Indicators$TopTissue==tissue,]),1,0)
  # table(VennFrame[,group])
}

# ASVs significantly associated with roots: 324
colSums2(as.matrix(VennFrame2[,"Roots"]))

# ASVs significantly associated with siliques: 33
colSums2(as.matrix(VennFrame2[,"Siliques"]))

# ASVs significantly associated with rosettes: 60
colSums2(as.matrix(VennFrame2[,"RosLeaves"]))

# ASVs significantly associated with stems: 41
colSums2(as.matrix(VennFrame2[,"Stems"]))

# ASVs significantly associated with cauline leaves: 2
colSums2(as.matrix(VennFrame2[,"CauLeaves"]))

ASVIndicators <- unique(c(rownames(PlantPart_Indicators),rownames(Stage_Indicators)))

####################################################################################################################################################

# Examine whether the ASVs are exclusive to specific tissues or stages.

# Focus on plant samples
physeq_plants <- subset_samples(physeq,PlantPart!="Soil")
physeq_plants <- prune_taxa(taxa_sums(physeq_plants)>0,physeq_plants)

# Get the columns of the sample data corresponding to the variables of interest and find all the combinations of values that occur in the dataset.
ConditionsFrame <- data.frame(unique(sample_data(physeq_plants)[,c("Year","Site","Stage","PlantPart")]),row.names=c())
ConditionsFrame <- data.frame(lapply(ConditionsFrame, as.character), stringsAsFactors=FALSE)

# Pervasive vs. Tissue-specific ASVs

# For each year and site, iterate through all the plant parts sampled and get the names of ASVs found in at least one sample of that part.
# Add these names to a list and then make a frequency table based on that list to show how many plant tissues each ASV was found in.
# If the ASV appeared in more than one plant part in at least one site/year, then it will be added to the list of pervasive ASVs.

ASVs_Pervasive <- c()
for(year in unique(ConditionsFrame$Year)){
  for(site in unique(ConditionsFrame$Site)){
    RecurrenceList <- c()
    for(part in unique(ConditionsFrame$PlantPart)){
      physeq_partition <-subset_samples(physeq_plants, PlantPart==part & Site==site & Year==year)
      physeq_partition <- prune_taxa(taxa_sums(physeq_partition)>0, physeq_partition)
      RecurrenceList <- c(taxa_names(physeq_partition),RecurrenceList)
    }
    assign(paste(site,year,"spatially","pervasive",sep="_"),names(table(RecurrenceList)[table(RecurrenceList)>1]))
    print(paste(site,year,"spatially","pervasive",sep="_"))
    ASVs_Pervasive  <- c(names(table(RecurrenceList)[table(RecurrenceList)>1]),ASVs_Pervasive)
    ASVs_Pervasive <- unique(ASVs_Pervasive)
  }
}

# Recurrent vs. Ephemeral ASVs

# For each year and site, iterate through all the stages sampled and get the names of ASVs found in at least one sample of that stage.
# Add these names to a list and then make a frequency table based on that list to show how many stages each ASV was found in.
# If the ASV appeared in more than one plant stage in at least one site/year, then it will be added to the list ASVs_Temporally_Recurrent.

ASVs_Recurrent <- c()
for(year in unique(ConditionsFrame$Year)){
  for(site in unique(ConditionsFrame$Site)){
    RecurrenceList <- c()
    for(stage in unique(ConditionsFrame[ConditionsFrame$Year==year & ConditionsFrame$Site==site,]$Stage)){
      physeq_partition <-subset_samples(physeq_plants, Stage==stage & Site==site & Year==year)
      physeq_partition <- prune_taxa(taxa_sums(physeq_partition)>0, physeq_partition)
      RecurrenceList <- c(taxa_names(physeq_partition),RecurrenceList)
    }
    assign(paste(site,year,"temporally","recurrent",sep="_"),names(table(RecurrenceList)[table(RecurrenceList)>1]))
    print(paste(site,year,"temporally","recurrent",sep="_"))
    ASVs_Recurrent  <- c(names(table(RecurrenceList)[table(RecurrenceList)>1]),ASVs_Recurrent)
    ASVs_Recurrent <- unique(ASVs_Recurrent)
  }
}
